name: PR Validation

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  validate-dotnet-8:
    name: Test on .NET 8.0
    uses: ./.github/workflows/build-and-test.yml
    with:
      dotnet-version: '8.0.x'
      upload-test-results: true

  validate-dotnet-9:
    name: Test on .NET 9.0
    uses: ./.github/workflows/build-and-test.yml
    with:
      dotnet-version: '9.0.x'
      upload-test-results: true

  validate-dotnet-10:
    name: Test on .NET 10.0
    uses: ./.github/workflows/build-and-test.yml
    with:
      dotnet-version: '10.0.x'
      upload-test-results: true
